### ISSUE TITLE
Abbr tag

### ISSUE THREAD

**Issue by warfarincoumadin** [glutanimate/mini-format-pack#11]
This seems like a fairly easy-to-implement feature of the old format pack.
There was a button that would add an abbreviation tag to the selected text as follows:

`<abbr title="Mini Format Pack">MFP</abbr>`

**Comment by glutanimate** [comment]
Hey @warfarincoumadin,
Super late, but thanks a bunch for the suggestion! I'm a bit hesitant about adding to many features to MFP (both in terms of maintenance and not overloading users with too many buttons/choices). So what I was wondering was: When do you typically use the `abbr` option? Could you give me an example of your workflow / use case? I feel like that would make it easier for me to assess whether this would be a good addition because I personally have never used `abbr` in my cards. Thanks again in advance!

**Comment by warfarincoumadin** [comment]
Hi Glutanimate,

Here is an example of what it does: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_abbr_test
Basically shows a tooltip on hover-over.
By now there are a few addons that make it quite easy to add html tags into anki cards - I think we can close the issue :)
